require: rubocop-rspec

Rails:
  Enabled: true

# Configure individual cops
Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 12

Rails/Date:
  EnforcedStyle: strict

# Enable individual cops that aren't on by default
Style/CollectionMethods:
  Enabled: true

Style/MethodCalledOnDoEndBlock:
  Enabled: true

# Disable individual cops
RSpec/AnyInstance:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

# All cops
AllCops:
  Exclude:
    - db/schema.rb
    - lib/templates/**/*
    - node_modules/**/*
    - vendor/**/*
