require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe MailBlastersController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # MailBlaster. As you add validations to MailBlaster, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MailBlastersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all mail_blasters as @mail_blasters" do
      mail_blaster = MailBlaster.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:mail_blasters)).to eq([mail_blaster])
    end
  end

  describe "GET #show" do
    it "assigns the requested mail_blaster as @mail_blaster" do
      mail_blaster = MailBlaster.create! valid_attributes
      get :show, params: {id: mail_blaster.to_param}, session: valid_session
      expect(assigns(:mail_blaster)).to eq(mail_blaster)
    end
  end

  describe "GET #new" do
    it "assigns a new mail_blaster as @mail_blaster" do
      get :new, params: {}, session: valid_session
      expect(assigns(:mail_blaster)).to be_a_new(MailBlaster)
    end
  end

  describe "GET #edit" do
    it "assigns the requested mail_blaster as @mail_blaster" do
      mail_blaster = MailBlaster.create! valid_attributes
      get :edit, params: {id: mail_blaster.to_param}, session: valid_session
      expect(assigns(:mail_blaster)).to eq(mail_blaster)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new MailBlaster" do
        expect {
          post :create, params: {mail_blaster: valid_attributes}, session: valid_session
        }.to change(MailBlaster, :count).by(1)
      end

      it "assigns a newly created mail_blaster as @mail_blaster" do
        post :create, params: {mail_blaster: valid_attributes}, session: valid_session
        expect(assigns(:mail_blaster)).to be_a(MailBlaster)
        expect(assigns(:mail_blaster)).to be_persisted
      end

      it "redirects to the created mail_blaster" do
        post :create, params: {mail_blaster: valid_attributes}, session: valid_session
        expect(response).to redirect_to(MailBlaster.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved mail_blaster as @mail_blaster" do
        post :create, params: {mail_blaster: invalid_attributes}, session: valid_session
        expect(assigns(:mail_blaster)).to be_a_new(MailBlaster)
      end

      it "re-renders the 'new' template" do
        post :create, params: {mail_blaster: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested mail_blaster" do
        mail_blaster = MailBlaster.create! valid_attributes
        put :update, params: {id: mail_blaster.to_param, mail_blaster: new_attributes}, session: valid_session
        mail_blaster.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested mail_blaster as @mail_blaster" do
        mail_blaster = MailBlaster.create! valid_attributes
        put :update, params: {id: mail_blaster.to_param, mail_blaster: valid_attributes}, session: valid_session
        expect(assigns(:mail_blaster)).to eq(mail_blaster)
      end

      it "redirects to the mail_blaster" do
        mail_blaster = MailBlaster.create! valid_attributes
        put :update, params: {id: mail_blaster.to_param, mail_blaster: valid_attributes}, session: valid_session
        expect(response).to redirect_to(mail_blaster)
      end
    end

    context "with invalid params" do
      it "assigns the mail_blaster as @mail_blaster" do
        mail_blaster = MailBlaster.create! valid_attributes
        put :update, params: {id: mail_blaster.to_param, mail_blaster: invalid_attributes}, session: valid_session
        expect(assigns(:mail_blaster)).to eq(mail_blaster)
      end

      it "re-renders the 'edit' template" do
        mail_blaster = MailBlaster.create! valid_attributes
        put :update, params: {id: mail_blaster.to_param, mail_blaster: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested mail_blaster" do
      mail_blaster = MailBlaster.create! valid_attributes
      expect {
        delete :destroy, params: {id: mail_blaster.to_param}, session: valid_session
      }.to change(MailBlaster, :count).by(-1)
    end

    it "redirects to the mail_blasters list" do
      mail_blaster = MailBlaster.create! valid_attributes
      delete :destroy, params: {id: mail_blaster.to_param}, session: valid_session
      expect(response).to redirect_to(mail_blasters_url)
    end
  end

end
